# Generated by Django 4.0.6 on 2022-10-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_raqam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raqam',
            name='raqam',
        ),
        migrations.AddField(
            model_name='raqam',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
